### ISSUE TITLE
Empty "Transaction ID" field in PiHole Query Log dashboard.

### ISSUE THREAD

**Issue by Sylver-Dragon** [ZachChristensen28/pihole_dns_app#12]
I recently installed this app from splunkbase and noticed an issue in one of the dahshboards.  
In the PiHole Query Log dashboard in the Query Log panel, the "Transaction ID" field is empty.  This appears to be caused by a mismatch in the line:  
`rename query as Query, transaction_id as "Transaction_ID"`
and later in the panel's query
`fields _time, Query, Host, "Forwarded Destination", "Message Type", "Query Type", Answer, "Reply Code", "Transaction ID"`

In the former line, there is an underscore between Transaction and ID, in the latter, that underscore is missing.  Making these two fields match corrects the issue.  The mismatch is between line 102 and 105 in:  
https://github.com/ZachChristensen28/pihole_dns_app/blob/master/default/data/ui/views/pihole_query_log.xml

**Comment by ZachChristensen28** [comment]
Thanks for pointing this out. I will include the fix in the next update.
