### ISSUE TITLE
Pihole Query Log -  Error in 'lookup' command:

### ISSUE THREAD

**Issue by thedownwardspiral** [ZachChristensen28/pihole_dns_app#41]
**Describe the bug**
Seeing "Error in 'lookup' command: Could not construct lookup 'pihole_dhcp_lease_lookup, dest_ip, as, src, OUTPUTNEW, dest_nt_host, as, Hostname'. See search.log for more details." in the Queries by Source over Time and Blocked Queryies by Source over Time panels on the Pihole Query Log.

**To Reproduce**
1. Go to Pi-hole DNS App for Splunk
2. Click on Pihole Query Log
3. See error

**Expected behavior**
Panels showing information as described by panel title.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/12749614/120953583-dd3c7e00-c712-11eb-869d-993f1e552d15.PNG)

**Version (please complete the following information):**
 - Splunk Version: 8.2.0
 - pihole_dns_app Version: 2.2
 - Pi-hole Version: Pi-hole v5.3.1 Web Interface v5.5 FTL v5.8.1

No enrichment data is being used.  The data is exported from the Pi-hole server to two flat files (for pihole and pihole:ftl) on the Splunk server via rsyslog.  Splunk is using the flat files as a data inputs and setting the sourcetypes, index to dns, and app to TA-pihole_dns.  This was working on Splunk 8.1.2 with the previous versions of the addon and app.

**Comment by ZachChristensen28** [comment]
I will run some tests and get back to you. 

Does this error only occur on this dashboard? Or do also see this error on the Pihole Overview dashboard on the bottom two panels (Top 10 sources & Top 10 Blocked Queries)?

**Comment by thedownwardspiral** [comment]
The two panels on the overview dashboard are showing the error described in issue #38

**Comment by ZachChristensen28** [comment]
I've been unable to replicate this issue on my development instances so far, but I will keep attempting. In the meantime, will you provide me the following information:

1. Run the following command in Splunk web and let me know if there are any errors: 
    
    ```shell
    | inputlookup pihole_dhcp_lease_lookup
    ```

   You should see something similar to this (0 output with no errors): 
   <img width="582" alt="image" src="https://user-images.githubusercontent.com/23529374/121077541-f980ff00-c794-11eb-926b-3f38e93fef70.png">

    Let me know if you see an output with errors.

1. Check the privileges of the lookup. Navigate to Settings > Lookups > Lookup Definitions.
1. Search for the `pihole_dhcp_lease_lookup` - The permissions should be global:
   
    <img width="1314" alt="image" src="https://user-images.githubusercontent.com/23529374/121078119-c25f1d80-c795-11eb-81a7-a10fefac5c31.png">

### Quick Fix

A quick fix could be editing the SPL of the panels that are affected and comment out the line ``| `pihole_enrich_hostname(src)` `` with three back ticks on both sides.

i.e.

````shell
``` | `pihole_enrich_hostname(src)` ```
````

<img width="779" alt="image" src="https://user-images.githubusercontent.com/23529374/121078383-21249700-c796-11eb-824f-c9174ce66f94.png">


I Look forward to your feedback and let me know if the quick fix works for you for the time being.

**Comment by thedownwardspiral** [comment]
So it looks like this was an underlying issue with an expired certificate causing the KV store process to crash.  I fixed that and almost everything works now (except for that thing with issue #38).
