### ISSUE TITLE
pihole_dhcp_lease_lookup missing attribute for dvc

### ISSUE THREAD

**Issue by malor38** [ZachChristensen28/pihole_dns_app#65]
The lookup file pihole_dhcp_lease_lookup contains DHCP information from all pi-hole servers that are acting as DHCP servers if you are running in multiple locations. However, there is no way to separate from which device each lease is related.

I would like to suggest that the saved search "Pihole - DHCP Leases Lookup - Gen" is updated with that attribute. I see no risk in adding this attribute to the lookup, it won't collide with any searches or dashboards.

My suggestion is to add the following to the search:

```
| tstats latest(All_Sessions.dest_nt_host) as "dest_nt_host", latest(All_Sessions.dest_mac) as "dest_mac" latest(dvc) as dvc from datamodel=Network_Sessions where sourcetype=pihole:dhcp by All_Sessions.dest_ip 
| `drop_dm_object_name(All_Sessions)` 
| eval _time=now()
| fields - count
| outputlookup create_empty=false createinapp=true override_if_empty=false pihole_dhcp_lease_lookup
```

**Comment by mljdivemaster** [comment]
pihole_dhcp_lease_lookup is a definition that points to a KV store, we need to update that definition as well. Missed that
